[/Script/EngineSettings.GameMapsSettings]
GlobalDefaultGameMode=/Script/Apex.ApexGameMode

[/Script/Engine.PhysicsSettings]
; Substepping = clé pour une sim véhicule stable et déterministe à haute vitesse.
bSubstepping=True
bSubsteppingAsync=False
MaxSubstepDeltaTime=0.008333
MaxSubsteps=6
DefaultGravityZ=-980.0

[/Script/Engine.Engine]
; Fixe le pas de simulation (optionnel mais recommandé pour la reproductibilité).
bUseFixedFrameRate=False
